import { expect, test } from "@playwright/test";
import { enterFreePractice, lobby } from "../world-tests/practiceFlow";
test.use({ locale: "en-US" });
test("English browser can change language and retain it across reloads and settings", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByRole("button", { name: "Play", exact: true })).toBeVisible();
  await expect(page.locator("html")).toHaveAttribute("lang", "en");
  await page.getByRole("combobox", { name: "Language / 言語" }).selectOption("ja");
  await expect(page.getByRole("button", { name: "はじめる", exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole("button", { name: "はじめる", exact: true })).toBeVisible();
  await page.getByRole("combobox", { name: "Language / 言語" }).selectOption("en");
  await page.getByRole("button", { name: "Play", exact: true }).click();
  await expect(lobby(page, "en")).toBeVisible();
  await page.getByRole("button", { name: "Settings", exact: true }).click();
  await expect(page.getByRole("slider", { name: "Music volume" })).toBeVisible();
  await page.getByRole("combobox", { name: "Language / 言語" }).selectOption("ja");
  await expect(page.getByRole("heading", { name: "整備と設定" })).toBeVisible();
});
test("English practice exposes translated instruments, camera controls and pause menu", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Play", exact: true }).click();
  await enterFreePractice(page, "en");
  await expect(page.getByRole("meter", { name: "Power", exact: true })).toBeVisible();
  await expect(page.getByRole("img", { name: /^Ground .* elevation .* world angle/ })).toBeVisible();
  await expect(page.getByRole("button", { name: "Pan using the overview", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Open settings", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Take a breather", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Surrender and finish", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Resume battle", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Take a breather", exact: true })).not.toBeVisible();
});
test("practice audio preferences persist into settings and after reload", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Play", exact: true }).click();
  await enterFreePractice(page, "en");
  await page.getByRole("button", { name: "Open settings", exact: true }).click();
  await page.getByRole("slider", { name: "Music volume" }).focus();
  await page.keyboard.press("Home");
  await page.getByRole("button", { name: "Mute", exact: true }).click();
  await page.getByRole("button", { name: "Back to practice", exact: true }).click();
  await page.getByRole("button", { name: "Back to preparation", exact: true }).click();
  await page.getByRole("button", { name: "Settings", exact: true }).click();
  await expect(page.getByRole("slider", { name: "Music volume" })).toHaveValue("0");
  await expect(page.getByRole("button", { name: "Unmute", exact: true })).toBeVisible();
  await page.reload();
  await page.getByRole("button", { name: "Play", exact: true }).click();
  await page.getByRole("button", { name: "Settings", exact: true }).click();
  await expect(page.getByRole("slider", { name: "Music volume" })).toHaveValue("0");
  await expect(page.getByRole("button", { name: "Unmute", exact: true })).toBeVisible();
});
