import { expect, test } from "@playwright/test";
import { beginFreePractice } from "../world-tests/practiceFlow";
const enter = async (page: import("@playwright/test").Page) => {
  await page.goto("/");
  await page.getByRole("button", { name: "はじめる", exact: true }).click();
  await beginFreePractice(page);
};
test("opening holds input until START and leaves a full turn", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await enter(page);
  const field = page.getByTestId("camera-world");
  await expect(page.locator(".battle-weapons button").first()).toBeDisabled();
  await expect(field).toHaveAttribute("data-loaded", "true", { timeout: 15000 });
  // 通常のカメラは表示倍率 9 を 7/9 に引いた 7 CSS px/cell（loadCameraScale）。
  await expect(field).toHaveAttribute("data-scale", "7");
  await expect(field).toHaveAttribute("data-opening", "true");
  await expect(page.locator(".battle-weapons button").first()).toBeDisabled();
  await page.screenshot({ path: "test-results/refinement-overview.png" });
  await expect(page.getByRole("status", { name: "START!" })).toBeVisible({ timeout: 10000 });
  await page.screenshot({ path: "test-results/refinement-start.png" });
  await expect(field).toHaveAttribute("data-opening", "false");
  await expect(page.locator(".battle-weapons button").first()).toBeEnabled();
  const dialBox = (await page.locator(".battle-angle").boundingBox())!;
  expect(dialBox.y + dialBox.height).toBeLessThanOrEqual(page.viewportSize()!.height);
  const reserve = page.getByRole("meter", { name: "残り移動", exact: true });
  await expect(reserve).toHaveAttribute("aria-valuenow", "30");
  await page.keyboard.press("ArrowRight");
  await expect(reserve).toHaveAttribute("aria-valuenow", "29");
  await page.screenshot({ path: "test-results/refinement-desktop.png" });
});
test("compact touch cross leaves over half the landscape for the world", async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 667, height: 375 }, hasTouch: true, locale: "ja-JP" });
  const page = await context.newPage();
  await enter(page);
  await expect(page.getByTestId("camera-world")).toHaveAttribute("data-opening", "false", { timeout: 15000 });
  const field = await page.getByTestId("camera-world").boundingBox();
  expect(field!.height).toBeGreaterThan(200);
  const left = await page.getByRole("button", { name: "左へ移動", exact: true }).boundingBox();
  const up = await page.getByRole("button", { name: "角度を上げる", exact: true }).boundingBox();
  const right = await page.getByRole("button", { name: "右へ移動", exact: true }).boundingBox();
  expect(left!.x).toBeLessThan(20);
  expect(up!.y).toBeLessThan(left!.y);
  expect(right!.x).toBeGreaterThan(up!.x);
  const reserve = page.getByRole("meter", { name: "残り移動", exact: true });
  await expect(reserve).toHaveAttribute("aria-valuenow", "30");
  await page.getByRole("button", { name: "右へ移動", exact: true }).tap();
  await expect(reserve).toHaveAttribute("aria-valuenow", "29");
  const gaugeBox = (await reserve.boundingBox())!;
  expect(gaugeBox.y + gaugeBox.height).toBeLessThanOrEqual(375);
  expect(gaugeBox.y).toBeGreaterThanOrEqual(up!.y);
  await page.screenshot({ path: "test-results/refinement-mobile.png" });
  await context.close();
});
