import { CLIENT_BUILD } from "@game/protocol/build";
import { expect, it } from "vitest";
import { WebSocket, WebSocketServer } from "ws";
import { attachRooms } from "../src/rooms/gateway";
it("isolates rooms, authenticates edits, starts chosen equipment and resumes the same member", async () => {
  const wss = new WebSocketServer({ host: "127.0.0.1", port: 0 });
  await new Promise<void>(r => wss.once("listening", r));
  const service = attachRooms(wss), sockets: WebSocket[] = [];
  const port = (wss.address() as { port: number }).port;
  const connect = async () => {
    const ws = new WebSocket(`ws://127.0.0.1:${port}`), messages: any[] = []; sockets.push(ws);
    ws.on("message", data => messages.push(JSON.parse(data.toString())));
    await new Promise<void>(r => ws.once("open", r));
    return { ws, messages, send: (m: unknown) => ws.send(JSON.stringify(m)), last: (type: string) => [...messages].reverse().find(m => m.type === type) };
  };
  const profile = { nickname: "Kero", loadout: ["triple", "laser"] };
  try {
    const a = await connect(), b = await connect(), other = await connect();
    a.send({ type: "room.create", build: CLIENT_BUILD, profile }); other.send({ type: "room.create", build: CLIENT_BUILD, profile });
    await expect.poll(() => a.last("room.snapshot")).toBeTruthy();
    await expect.poll(() => other.last("room.snapshot")).toBeTruthy();
    const roomId = a.last("room.snapshot").room.roomId, owner = a.last("room.welcome").playerId;
    b.send({ type: "room.join", build: CLIENT_BUILD, roomId, profile });
    await expect.poll(() => a.last("room.snapshot").room.members.length).toBe(2);
    const guest = b.last("room.welcome").playerId;
    const edit = (client: typeof a, type: string, extra: object) => client.send({ version: 2, type, roomId, revision: a.last("room.snapshot").room.revision, ...extra });
    edit(other, "room.ready", { ready: true });
    await expect.poll(() => other.last("room.error")?.reason).toBe("wrong-room");
    edit(b, "room.assignTeam", { playerId: owner, teamId: "t1" });
    await expect.poll(() => b.last("room.error")?.reason).toBe("not-owner");
    edit(a, "room.assignTeam", { playerId: owner, teamId: "t0" });
    await expect.poll(() => a.last("room.snapshot").room.members[0].teamId).toBe("t0");
    edit(b, "room.assignTeam", { playerId: guest, teamId: "t1" });
    await expect.poll(() => a.last("room.snapshot").room.members[1].teamId).toBe("t1");
    edit(a, "room.ready", { ready: true }); edit(b, "room.ready", { ready: true });
    await expect.poll(() => a.last("room.snapshot").room.members.every((p: any) => p.ready)).toBe(true);
    edit(a, "room.start", {});
    await expect.poll(() => a.last("lab.frame")).toBeTruthy();
    expect(a.last("lab.frame").players).toHaveLength(2);
    expect(a.last("lab.frame").map.id).toBe("moss-valley");
    expect(a.last("lab.frame").map.surface).toHaveLength(500);
    expect(a.last("lab.frame")).not.toHaveProperty("windState");
    expect(a.last("lab.frame").wind).toBeGreaterThanOrEqual(-10);
    expect(a.last("lab.frame").wind).toBeLessThanOrEqual(10);
    expect(other.last("lab.frame")).toBeUndefined();
    expect(other.last("room.snapshot").room.members).toHaveLength(1);
    const frame = a.last("lab.frame"), shooter = frame.actorId === owner ? a : b;
    shooter.send({ type: "turn.fire", version: 2, matchId: frame.matchId, turnId: frame.turnId, commandId: "f1", ackMoveSeq: 0, slot: 0, facing: 1, elevation: 45, power: 50 });
    await expect.poll(() => a.last("lab.frame").phase).toBe("replaying");
    expect(a.last("lab.frame").replay.shooter.weapon).toBe("triple");
    expect(a.last("lab.frame").replay.paths).toHaveLength(3);
    const token = b.last("room.welcome").token;
    b.ws.close(); await new Promise<void>(r => b.ws.once("close", r));
    const resumed = await connect(); resumed.send({ type: "room.resume", build: CLIENT_BUILD, token });
    await expect.poll(() => resumed.last("room.welcome")?.playerId).toBe(guest);
    expect(resumed.last("lab.frame").matchId).toBe(frame.matchId);
    const intruder = await connect(); intruder.send({ type: "room.resume", build: CLIENT_BUILD, token });
    await expect.poll(() => intruder.last("room.error")?.reason).toBe("invalid-session");
    intruder.send({ type: "room.join", build: CLIENT_BUILD, roomId, profile });
    await expect.poll(() => intruder.last("room.error")?.reason).toBe("locked");
    a.send({ type: "room.leave" });
    await expect.poll(() => resumed.last("lab.frame")?.phase, { timeout: 10000 }).toBe("finished");
    resumed.send({ type: "lab.rematch", matchId: frame.matchId });
    await expect.poll(() => resumed.last("room.snapshot")?.room.phase).toBe("waiting");
    expect(resumed.last("room.snapshot").room.ownerId).toBe(guest);
    expect(resumed.last("room.snapshot").room.members).toHaveLength(1);
  } finally { sockets.forEach(s => s.terminate()); service.close(); await new Promise<void>(r => wss.close(() => r())); }
}, 20000);
