/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.cpu.jsonc --include-runtime=false --env-interface=CpuWorkerEnv src/cf/cpu-env.d.ts` (hash: 5ef352651083d60b4209ae4056efcce7)
interface __BaseEnv_CpuWorkerEnv {
	CPU_LIMITER: RateLimit;
	CPU_TOTAL_LIMITER: RateLimit;
	ALLOWED_ORIGINS: "https://fortress-9hj.pages.dev";
	JEV_MODEL: "jev-latest";
	JEV_ENABLED: "true";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./cpu");
	}
	interface Env extends __BaseEnv_CpuWorkerEnv {}
}
interface CpuWorkerEnv extends __BaseEnv_CpuWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "JEV_MODEL" | "JEV_ENABLED">> {}
}
