import { afterEach, expect, it, vi } from "vitest";
import { measureLatency } from "../src/networkLab/latency";
afterEach(() => { vi.useRealTimers(); vi.unstubAllGlobals(); });
it("measures only matching replies, clears stale values, and stops on cleanup", () => {
  vi.useFakeTimers({ toFake: ["setInterval", "clearInterval", "performance"] });
  vi.stubGlobal("document", { hidden: false });
  vi.stubGlobal("WebSocket", { OPEN: 1 });
  const socket = Object.assign(new EventTarget(), { readyState: 1, send: vi.fn() });
  const update = vi.fn();
  const stop = measureLatency(socket as unknown as WebSocket, update);
  const reply = (nonce: number) => socket.dispatchEvent(new MessageEvent("message", { data: JSON.stringify({ type: "room.pong", nonce }) }));
  vi.advanceTimersByTime(350);
  reply(99);
  expect(update).toHaveBeenLastCalledWith(null);
  reply(1);
  expect(update).toHaveBeenLastCalledWith(350);
  vi.advanceTimersByTime(9650);
  expect(update).toHaveBeenLastCalledWith(null);
  reply(2);
  expect(update).toHaveBeenLastCalledWith(null);
  vi.advanceTimersByTime(20);
  reply(3);
  expect(update).toHaveBeenLastCalledWith(20);
  socket.dispatchEvent(new Event("close"));
  expect(update).toHaveBeenLastCalledWith(null);
  stop();
  const calls = socket.send.mock.calls.length;
  vi.advanceTimersByTime(10000);
  expect(socket.send).toHaveBeenCalledTimes(calls);
});
