import { expect, test } from "@playwright/test";

test("CPU戦の設定・自動射撃・降参・再戦・退出", async ({ page }) => {
  test.setTimeout(90000);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.addInitScript(() => { Math.random = () => 0.5; });
  await page.goto("/");
  await page.getByRole("button", { name: "はじめる", exact: true }).click();
  await page.getByRole("button", { name: "プラクティス", exact: true }).click();
  await page.getByRole("button", { name: "CPU戦", exact: true }).click();
  await expect(page.getByRole("heading", { name: "CPU戦", exact: true })).toBeVisible();
  await page.goBack();
  await page.getByRole("button", { name: "CPU戦", exact: true }).click();
  await expect(page.getByRole("button", { name: "CPU戦をはじめる" })).toBeInViewport();
  await expect(page.getByRole("combobox", { name: "CPUレベル" })).toHaveValue("normal");
  await page.getByRole("combobox", { name: "CPUレベル" }).selectOption("easy");
  await expect(page.locator("#cpu-level-hint")).toContainText("大きく");
  await page.getByRole("button", { name: "CPU戦をはじめる" }).click();
  await expect(page.locator(".cpu-level-label")).toHaveText("やさしい");
  const fire = page.getByRole("button", { name: "標準砲", exact: true });
  await expect(fire).toBeEnabled({ timeout: 25000 });
  await page.keyboard.down("Space");
  await page.waitForTimeout(100);
  await page.keyboard.up("Space");
  await expect.poll(() => page.evaluate(() => {
    const view = window.__fortress?.getView() as { cpuPose?: { elevation: number } | null } | undefined;
    return view?.cpuPose?.elevation;
  }), { timeout: 25000, intervals: [50] }).toEqual(expect.any(Number));
  await page.keyboard.press("KeyE");
  await page.keyboard.down("ArrowUp");
  await page.waitForTimeout(150);
  await page.keyboard.up("ArrowUp");
  await expect(page.getByRole("button", { name: "掘削弾", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.screenshot({ path: "/tmp/practice-cpu-aim.png" });
  await expect.poll(() => page.evaluate(() => window.__fortress?.getView().phase === "replaying" ? window.__fortress.getView().currentSeat : null), { timeout: 25000, intervals: [50] }).toBe(1);
  await expect(fire).toBeEnabled();
  expect(await page.locator(".battle-weapons button").evaluateAll(buttons => buttons.map(button => button.getAttribute("aria-label")))).toEqual(["標準砲", "掘削弾"]);
  await expect.poll(() => page.evaluate(() => window.__fortress?.getView().mismatches)).toBe(0);
  await page.screenshot({ path: "/tmp/practice-cpu-portrait.png" });
  await page.getByRole("button", { name: "設定を開く", exact: true }).click();
  await page.getByRole("button", { name: "降参して対戦を終える" }).click();
  await expect(page.locator(".world-result-screen")).toBeVisible({ timeout: 25000 });
  await expect(page.locator(".world-result-screen")).toContainText("CPU");
  await page.getByRole("button", { name: "もう一度プレイ" }).click();
  await expect(page.locator(".practice-battle-status")).toContainText("CPU");
  await expect(page.locator(".cpu-level-label")).toHaveText("やさしい");
  await page.getByRole("button", { name: "設定を開く", exact: true }).click();
  await page.getByRole("button", { name: "プラクティスへ戻る", exact: true }).click();
  await expect(page.getByRole("heading", { name: "プラクティス", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "自由練習", exact: true }).click();
  await page.getByRole("button", { name: "自由練習をはじめる" }).click();
  await expect(page.locator(".practice-battle-status")).toHaveText("自由練習");
});

test("タッチでも敵の手番は準備だけを操作できる", async ({ browser }) => {
  const context = await browser.newContext({ hasTouch: true, viewport: { width: 390, height: 844 }, locale: "ja-JP" });
  const page = await context.newPage();
  await page.addInitScript(() => { Math.random = () => 0.25; });
  await page.goto("/");
  await page.getByRole("button", { name: "はじめる", exact: true }).tap();
  await page.getByRole("button", { name: "プラクティス", exact: true }).tap();
  await page.getByRole("button", { name: "CPU戦", exact: true }).tap();
  await page.getByRole("button", { name: "CPU戦をはじめる" }).tap();
  const aim = page.getByRole("button", { name: "角度を上げる", exact: true });
  await expect(aim).toBeEnabled({ timeout: 15000 });
  await expect(page.getByRole("button", { name: "発射", exact: true })).toBeDisabled();
  await expect(page.getByRole("button", { name: "左へ移動", exact: true })).toBeDisabled();
  await aim.tap();
  await page.getByRole("button", { name: "掘削弾", exact: true }).tap();
  await expect(page.getByRole("button", { name: "掘削弾", exact: true })).toHaveAttribute("aria-pressed", "true");
  await context.close();
});
