import { expect, test } from "@playwright/test";
test("wreck sinks its body and lowers its barrel while keeping the tracks grounded", async ({ page }) => {
  await page.goto("/?prototype=world");
  const poses = await page.evaluate(async () => {
    const source = "/src/prototype/spriteTank.ts";
    const { loadSpriteTanks } = await import(/* @vite-ignore */ source);
    const factory = await loadSpriteTanks();
    const tank = factory.create({}, "wreck");
    const pose = { x: 100, y: 90, tilt: 0, facing: 1, elevation: 70, hp: 100, visible: true, flash: false, aiming: true };
    const read = () => {
      const rig = tank.world.children[0];
      const tracks = rig.getChildByLabel("tracks");
      const body = rig.getChildByLabel("body");
      const gun = body?.getChildByLabel("gun");
      return { ground: tank.world.y, tracksY: tracks?.y, bodyY: body?.y, bodyX: body?.x, weaponX: gun?.children[0].x, gray: Boolean(rig.filters?.length), barrel: gun?.rotation, aim: gun?.children[1].visible };
    };
    tank.setPose(pose, 3);
    const alive = read();
    factory.setWeapon(0, "triple");
    tank.setPose({ ...pose, shotFlashes: [{ age: 30, index: 0 }, { age: 30, index: 1 }, { age: 30, index: 2 }], recoil: 3 }, 3);
    const gun = tank.world.children[0].getChildByLabel("body").getChildByLabel("gun");
    const muzzle = () => gun.children.filter((child: { label: string }) => child.label.startsWith("muzzle-")).map((child: { x: number; y: number; visible: boolean }) => ({ x: child.x, y: child.y, visible: child.visible }));
    const activeMuzzle = muzzle();
    tank.setPose({ ...pose, recoil: 3 }, 3);
    const firing = read();
    tank.setPose({ ...pose, hp: 0 }, 3);
    const destruction = read();
    await new Promise(resolve => setTimeout(resolve, 620));
    tank.setPose({ ...pose, hp: 0 }, 3);
    const wreck = read();
    tank.setPose({ ...pose, hp: 0, elevation: 10, facing: -1 }, 3);
    const otherAim = read();
    tank.setPose(pose, 3);
    const restored = read();
    const stoppedMuzzle = muzzle();
    tank.destroy(); factory.destroy();
    return { alive, firing, wreck, otherAim, restored, destruction, activeMuzzle, stoppedMuzzle };
  });
  expect(poses.activeMuzzle).toEqual([-103 / 12, -8, -89 / 12].map(y => ({ x: -51 / 12, y, visible: true })));
  expect(poses.stoppedMuzzle.every((sprite: { visible: boolean }) => !sprite.visible)).toBe(true);
  expect(poses.firing.bodyX).toBeCloseTo(-2 / 12);
  expect(poses.firing.weaponX).toBeCloseTo(-8 - 3 / 12);
  expect(poses.firing.tracksY).toBe(poses.alive.tracksY);
  expect(poses.destruction.bodyY).toBe(0);
  expect(poses.destruction.gray).toBe(false);
  expect(poses.wreck.gray).toBe(true);
  expect(poses.wreck.bodyY).toBeCloseTo(8 / 12);
  expect(poses.wreck.barrel).toBeCloseTo(18 * Math.PI / 180);
  expect(poses.wreck.aim).toBe(false);
  expect(poses.wreck.ground).toBe(poses.alive.ground);
  expect(poses.wreck.tracksY).toBe(poses.alive.tracksY);
  expect(poses.otherAim).toEqual(poses.wreck);
  expect(poses.restored).toEqual(poses.alive);
});
