"""Compile an image alpha channel into deterministic collision columns (Pillow).

This reads the source without modifying it. Runtime clients never decode an image
for physics. Usage: python3 tools/import-terrain-mask.py source.png output.ts
"""
import hashlib
import json
import sys
from pathlib import Path
from PIL import Image

WIDTH, HEIGHT = 400, 225
THRESHOLD = 160


def columns_from_alpha(path):
    image = Image.open(path).convert("RGBA")
    alpha = image.getchannel("A")
    if alpha.getextrema()[0] == 255:
        raise ValueError("Terrain must have real transparent air")
    samples = alpha.resize((WIDTH, HEIGHT), Image.Resampling.BOX)
    cells = [[samples.getpixel((x, y)) >= THRESHOLD for x in range(WIDTH)] for y in range(HEIGHT)]
    columns = []
    for x in range(WIDTH):
        runs, start = [], None
        for y in range(HEIGHT + 1):
            solid = y < HEIGHT and cells[y][x]
            if solid and start is None:
                start = y
            if not solid and start is not None:
                # Tiny leaves/roots are decoration, not load-bearing platforms.
                if y - start >= 4:
                    runs.append([start, y])
                start = None
        columns.append(runs)
    return columns


def main():
    source, destination = map(Path, sys.argv[1:3])
    columns = columns_from_alpha(source)
    digest = hashlib.sha256(source.read_bytes()).hexdigest()
    destination.write_text("// Generated by tools/import-terrain-mask.py; do not hand-edit.\n"
        f'export const ROCK_ARCH_SOURCE_SHA256 = "{digest}";\n'
        f"export const ROCK_ARCH_COLUMNS: readonly (readonly (readonly [number, number])[])[] = {json.dumps(columns, separators=(',', ':'))};\n")
    print(f"Compiled {WIDTH}x{HEIGHT} collision mask; alpha threshold {THRESHOLD}; source {digest}")


if __name__ == "__main__":
    main()
