"""Compile an image alpha channel into deterministic collision columns (Pillow).

This reads the source without modifying it. Runtime clients never decode an image
for physics. Usage: python3 tools/import-terrain-mask.py source.png output.ts
"""
import hashlib
import json
import sys
from pathlib import Path
from PIL import Image

WIDTH, HEIGHT = 400, 225
THRESHOLD = 160


def columns_from_alpha(path, width=WIDTH, height=HEIGHT):
    if not 1 <= width <= 500 or not 1 <= height <= 225:
        raise ValueError("Terrain dimensions exceed validated bounds")
    image = Image.open(path).convert("RGBA")
    alpha = image.getchannel("A")
    if alpha.getextrema()[0] == 255:
        raise ValueError("Terrain must have real transparent air")
    samples = alpha.resize((width, height), Image.Resampling.BOX)
    cells = [[samples.getpixel((x, y)) >= THRESHOLD for x in range(width)] for y in range(height)]
    columns = []
    for x in range(width):
        runs, start = [], None
        for y in range(height + 1):
            solid = y < height and cells[y][x]
            if solid and start is None:
                start = y
            if not solid and start is not None:
                # Tiny leaves/roots are decoration, not load-bearing platforms.
                if y - start >= 4:
                    runs.append([start, y])
                start = None
        columns.append(runs)
    return columns


def main():
    source, destination = map(Path, sys.argv[1:3])
    prefix = sys.argv[3] if len(sys.argv) > 3 else "ROCK_ARCH"
    if not prefix.isidentifier() or not prefix.isascii():
        raise ValueError("Invalid TypeScript symbol prefix")
    width = int(sys.argv[4]) if len(sys.argv) > 4 else WIDTH
    height = int(sys.argv[5]) if len(sys.argv) > 5 else HEIGHT
    columns = columns_from_alpha(source, width, height)
    digest = hashlib.sha256(source.read_bytes()).hexdigest()
    destination.write_text("// Generated by tools/import-terrain-mask.py; do not hand-edit.\n"
        f'export const {prefix}_SOURCE_SHA256 = "{digest}";\n'
        f"export const {prefix}_COLUMNS: readonly (readonly (readonly [number, number])[])[] = {json.dumps(columns, separators=(',', ':'))};\n")
    print(f"Compiled {width}x{height} collision mask; alpha threshold {THRESHOLD}; source {digest}")


if __name__ == "__main__":
    main()
